Remove long out of use workaround
hallowelt/mediawiki pull request #135
Opened 2020-12-14 14:04 UTC by pwirth

Remove long out of use workaround for required class WikiAdmin

ERM:17148
[3.2]

2020-12-31 10:25 UTC, mrglaser commented
Is there a reason we need to keep the settings file at all? I'd rather remove it completely.

2020-12-31 10:26 UTC, mrglaser commented on settings.d/020-BlueSpiceWikiAdmin.php
> +return;
I suggest we simply delete the whole file.

2020-12-31 10:26 UTC, mrglaser requested changes
I think it makes more sense to delete the whole file

2021-01-07 10:27 UTC, osnard commented
Yes, please remove the whole file. Also please provide a PR for `REL1_35`. Github does not allow cherry-picking from the web :|

2021-01-11 07:44 UTC, pwirth commented
This file can not be deleted, as it needs to overwrite the current existing file when the system is updated!

2021-01-11 10:46 UTC, mrglaser commented
Moved the discussion to the ticket 17148. Once we come up with a conclusion, I will update here.

2021-07-01 16:04 UTC, mrglaser commented
As per #17148: The proposed solution is ok for BlueSpice 3.x and 3.2.x to maintain updateability. For BlueSpice 4 (master branch), please remove the file.

2021-09-15 13:53 UTC, merged